package mapreduce

// Interface defining the structure of the "map" function
type Mapper interface {
	Map(key, value string) []KeyValue
}

// Represents the "intermediate" key Value data generated by the Map function
type KeyValue struct {
	Key   string
	Value string
}
